### ISSUE TITLE
New admin toggle switch UI

### ISSUE THREAD

**Issue by pderksen** [moonstonemedia/WP-Simple-Pay-Lite-for-Stripe#15]
It's confusing for some. Need to put in a cleaner one.

**Comment by pderksen** [comment]
@nickyoung87 No rush but can you do a few tests on `css-toggle-switch` when you can? Test a fresh install to make sure it defaults to Test mode also.

**Comment by nickyoung87** [comment]
@pderksen This is what I see on a fresh install. http://screencast.com/t/UHGeJPnNjwd

**Comment by nickyoung87** [comment]
@pderksen Previously was a technical difficulty issue on my side. Everything looks great now!
