### ISSUE TITLE
Stripe charge object

### ISSUE THREAD

**Issue by deepanshu-kumar** [moonstonemedia/WP-Simple-Pay-Lite-for-Stripe#19]
I am using wordpress stripe pro plugin.In this I am using shortcode as you have mentioned in your documentation. On my website first user payment using stripe then he purchase some item. This purchase is confirmation based from admin on my website. I want to make by default capture false. If admin confirms then I want to update capture true on that charge object. I have used capture on my shortcode but this is not working. Please give me some suggestion how can I do this.

**Comment by pderksen** [comment]
This GitHub repository is intended for the Lite version of the plugin only.

You can find our docs here:
https://wpsimplepay.com/docs/

You can send us questions about the Pro plugin here:
https://wpsimplepay.com/contact/

Thanks.
