### ISSUE TITLE
Tweak ignored formatting in upgrade notice.

### ISSUE THREAD

**Issue by pderksen** [moonstonemedia/WP-Simple-Pay-Lite-for-Stripe#34]
In the `==Upgrade Notice==` section of the readme.txt, formatting such as `<code>` tags & line breaks were ignored. Adjust accordingly next release.

![image](https://user-images.githubusercontent.com/79667/30084634-0dd92a12-9248-11e7-9033-f6ad9fbc1d57.png)

Old content:

= 2.0.1 =

The payment form builder has been completely redone, but should be much simpler.

Your existing payment forms using the legacy <code>[stripe]</code> shortcode should continue to work, but it is highly recommended to use the new settings going forward.

**Comment by nickyoung87** [comment]
@pderksen If you want this in 2.0.2 go ahead and add it soon so that way when I build everything tonight we don't have to undo anything for this if you want it in there.

**Comment by pderksen** [comment]
@nickyoung87 Done. I also want to see if it picks up the notice when it's set to `2.0.0` but you're upgrading from 1.x to 2.0.2. Keep this open until we confirm.

**Comment by pderksen** [comment]
@nickyoung87 I was wrong on the upgrade notice. You do have to update it to the exact current version if you want it to show up.

**Comment by pderksen** [comment]
@nickyoung87 Actually now I don't know if I tested it right. :)

Either way you pushed it and we can leave this alone.

**Comment by nickyoung87** [comment]
Well I do think it matters for the upgrade version number but yeah I guess I am not 100% sure about that too. I did upload the new readme and confirmed it works after that.
