### ISSUE TITLE
Add Pro upgrade links back to admin menu & plugins page.

### ISSUE THREAD

**Issue by pderksen** [moonstonemedia/WP-Simple-Pay-Lite-for-Stripe#35]
These two upgrade links didn't make it into the v1.6 to v2 refactor. Let's add them back in.

Admin menu:

![image](https://user-images.githubusercontent.com/79667/30085273-8b620be6-924a-11e7-9c3d-d08344dcdda6.png)

Plugins page:

![image](https://user-images.githubusercontent.com/79667/30085288-9a0dd1fc-924a-11e7-89ee-01f950d036b8.png)

Change the plugins page text to "Upgrade to Pro" instead of "Purchase Pro" for consistency.

**Comment by nickyoung87** [comment]
Alright this is done. I converted everything into core. I have left the legacy stuff in place though in case someone runs the legacy + SP2 to avoid possible errors.

Another thing to note is the placement of the "Upgrade to Pro" action link on the plugins page. It is now before the "Deactivate" and "Edit" links. If this is a big deal then let me know and I will rework that area so we can have it back the other way.

**Comment by pderksen** [comment]
@nickyoung87 Shift it to the right-most link if you could like before.

No need to add it to the changelog.

**Comment by nickyoung87** [comment]
Alright good to go here.

**Comment by pderksen** [comment]
@nickyoung87 Neither of these links are entirely correct.

The submenu link is not URL-encoding the GA campaign vars properly.

`https://wpsimplepay.com/lite-vs-pro/?utm_source=inside-plugin#038;utm_medium=link&#038;utm_campaign=lite-plugin&#038;utm_content=1`

The plugin listing link doesn't include GA campaign vars at all.

`https://wpsimplepay.com/lite-vs-pro/`

**Comment by nickyoung87** [comment]
@pderksen Should be good here now.
