### ISSUE TITLE
Extend webhook actions

### ISSUE THREAD

**Issue by psaikali** [moonstonemedia/WP-Simple-Pay-Lite-for-Stripe#37]
Hi there,

I need to have a more granular access to webhooks triggered during a subscription lifecycle (pro version).

I found some hooks in the webhooks.php file, but I think it could be extended to make it more flexible for developers to catch Stripe webhooks calls and easily add new logics.

For example : 
`do_action( 'simpay_webhook_invoice_payment_succeeded' );`
doesn't pass any parameter, but passing the `$event` parameter would be really useful, to get subscription metadata, customer data and such.

A good idea would be to trigger this action a couple of lines later, so the `$invoice` and `$subscription` variables could be passed too :
`do_action( 'simpay_webhook_invoice_payment_succeeded', $event, $invoice, $subscription );`

Last but not least, I think a global `simpay_webhook_event` would be perfect so we can hook on any event, like such : 
![capture 2017-10-21 a 12 15 30](https://user-images.githubusercontent.com/1606655/31850818-c5fe8f44-b659-11e7-8e6c-1dfbe81205eb.jpg)

Otherwise, thanks for the plugin :)

**Comment by nickyoung87** [comment]
@psaikali Thanks for the great suggestions!

Keep an eye out for the upcoming release for these changes.
