### ISSUE TITLE
same customer, 2 charges == 2 customers in control panel

### ISSUE THREAD

**Issue by rhd** [moonstonemedia/WP-Simple-Pay-Lite-for-Stripe#6]
Hi,

I had a customer do two charges today with the exact same info and now they are listed twice on the stripe.com page here: https://dashboard.stripe.com/customers

Doing a bit of googling, stripe says it's the job of their api consumer to dedupe the customers:
https://groups.google.com/a/lists.stripe.com/forum/#!topic/api-discuss/aorqSVqr06A

"To ensure card unicity, you should look at the `fingerprint` property 
on the Token [1] or Card [2] object which uniquely identifies a 
specific card number in your account. You'd store this along with the 
expiration date (not used when calculating the fingerprint) so that 
whenever you get a new card token you can try to match that card to an 
existing customer in your account. "

Is it possible to add this?

Thanks!

**Comment by nickyoung87** [comment]
Yes this is just currently how our plugin works. It may change in the future, but at this point I can't make any promises.

**Comment by planetahuevo** [comment]
+1 on this, I think this is a feature request, not a questions really.
