### ISSUE TITLE
is check_wp_version() method in class Stripe_Checkout_Notices needed?

### ISSUE THREAD

**Issue by nekojira** [moonstonemedia/WP-Simple-Pay-Lite-for-Stripe#8]
this check looks like redundant

https://github.com/moonstonemedia/WP-Simple-Pay-Lite-for-Stripe/blob/dev/stripe/classes/class-stripe-checkout-notices.php#L62

a requirements check is being done at plugin load:

https://github.com/moonstonemedia/WP-Simple-Pay-Lite-for-Stripe/blob/dev/stripe/stripe-checkout.php#L40

also, usage of `wp_die()` may break user site, a more graceful method is to return void and prevent code to run further

lastly, if a minimum version of wp isn't just 'recommended' but running a lower version actually causes fatal compatibility problems perhaps the script should halt such as here https://github.com/moonstonemedia/WP-Simple-Pay-Lite-for-Stripe/blob/dev/stripe/stripe-checkout.php#L72 - if not, just print notice, perhaps once only

**Comment by nickyoung87** [comment]
@nekojira Good point. I removed the redundant check.
